### ISSUE TITLE
Feedback Colors broken in 2.2.0 build 3352

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-bmd-atem#143]
The ATEM module's Feedback colors don't show up in 2.2.0 build 3352.

The colors show up when running 2.1.3, but not in 2.2.0 build 3352. 

See screenshot of the two (2.2.0 on left, 2.1.3 on right).

<img width="1072" alt="Screen Shot 2021-06-03 at 8 28 42 AM" src="https://user-images.githubusercontent.com/76959770/120647207-55235380-c448-11eb-88df-171690eeb729.png">

**Comment by Julusian** [comment]
Should be fixed now

**Comment by davidjoshuaford** [comment]
Hi @Julusian, I think something in build 3378 corrupted my config database (15" Macbook Pro, OS11.4). 

I've tried this on two different Mac logins with the same effect. 

The web UI hangs on "syncing". I later updated to 3379, but the same effect. I then deleted the companion folder from users, and was able to get back into the blank web UI again. 

I imported my previously saved config file, but no more than the first 19 pages have imported - the remainder are blank. 

Log reads: 

> 21.06.08 19:31:26 instance(XRLp8ZiMQ): Instance failed to launch: mod is not a constructor
> 21.06.08 19:31:26 module(generic-osc): Error loading module: Error: Cannot find module './upgrades' Require stack: - /Applications/Companion 2.2.0-3379.app/Contents/Resources/app.asar/node_modules/companion-module-generic-osc/osc.js - /Applications/Companion 2.2.0-3379.app/Contents/Resources/app.asar/lib/instance.js - /Applications/Companion 2.2.0-3379.app/Contents/Resources/app.asar/app.js - /Applications/Companion 2.2.0-3379.app/Contents/Resources/app.asar/electron.js -
> 21.06.08 19:31:26 instance(5Ye8ATKMB): Instance failed to launch: mod is not a constructor
> 21.06.08 19:31:26 module(generic-osc): Error loading module: Error: Cannot find module './upgrades' Require stack: - /Applications/Companion 2.2.0-3379.app/Contents/Resources/app.asar/node_modules/companion-module-generic-osc/osc.js - /Applications/Companion 2.2.0-3379.app/Contents/Resources/app.asar/lib/instance.js - /Applications/Companion 2.2.0-3379.app/Contents/Resources/app.asar/app.js - /Applications/Companion 2.2.0-3379.app/Contents/Resources/app.asar/electron.js -

I quit Chrome and Companion and restarted Companion, and it's back to the "Syncing".. 

<img width="1286" alt="Screen Shot 2021-06-08 at 7 45 15 PM" src="https://user-images.githubusercontent.com/76959770/121271648-1f3ffe00-c892-11eb-827f-e9ef5f946d64.png">

**Comment by Julusian** [comment]
Looks like I made a typo in generic-osc. I'll fix it in the morning. Hopefully it's just that and not actual corruption

**Comment by davidjoshuaford** [comment]
Thanks! 

I've been backing up my work as I go, so hopefully the exported Config is fine as well. 

Will check back tomorrow. Cheers, David

**Comment by Julusian** [comment]
hopefully fixed now

**Comment by davidjoshuaford** [comment]
@Julusian I've tried build 3380, but it still hangs on Syncing... any ideas what I should try? thanks

**Comment by Julusian** [comment]
Could you send me a copy of your database, so I can try it myself? If you would rather not attach it here, dm me on slack or email `git@julusian.co.uk`
